
```{r}
exposure <- ct_exposure
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(here)
```




```{r}
ct_results <- read_csv(here('data/processed/extraction_2024-04-14/census-tract-results/subset_census_tract_results.csv'))
```

```{r}
ct_v1_2019 <- ct_results %>% 
  filter(scen_id == "reference case-setback_3200ft-no quota-price floor-no ccs-low innovation-no tax-0") %>% 
  filter(year == 2019)

ct_v2_2019 <- ct_results %>% 
  filter(scen_id == "low oil price-setback_3200ft-no quota-carbon_target_90perc_reduction-no ccs-low innovation-no tax-1") %>% 
  filter(year == 2019)
```


```{r}
# C.1 -------------------
ct_results <- read_csv(here('data/processed/extraction_2024-04-14/census-tract-results/subset_census_tract_results.csv'))

ct_v2_2019 <- ct_results %>% 
  filter(scen_id == "low oil price-setback_3200ft-no quota-carbon_target_90perc_reduction-no ccs-low innovation-no tax-1") %>% 
  filter(year == 2019)

ct_v2_2019 %>%
  group_by(disadvantaged) %>%
  summarise(
    min_pm25 = min(total_pm25),
    q1_pm25 = quantile(total_pm25, 0.25),
    median_pm25 = median(total_pm25),
    mean_pm25 = mean(total_pm25),
    q3_pm25 = quantile(total_pm25, 0.75),
    max_pm25 = max(total_pm25),
    sd_pm25 = sd(total_pm25),
    n = n()
  )
```


```{r}
ggplot(ct_v1_2019, aes(x = total_pm25, fill = disadvantaged)) +
  geom_histogram(alpha = 0.5, position = "identity", bins = 30) +
  labs(x = "Total PM2.5", y = "Count", fill = "Disadvantaged") +
  theme_minimal()
```



```{r}
ggplot(ct_v1_2019, aes(x = disadvantaged, y = total_pm25, fill = disadvantaged)) +
  geom_violin(trim = FALSE) +
  # geom_boxplot(width = 0.2, position = position_dodge(0.9), fill = "white", outlier.shape = NA) +
  labs(x = "Disadvantaged", y = "Total PM2.5", fill = "Disadvantaged") +
  theme_minimal() +
  theme(legend.position = "none")
```






